---
- name: test playbook 
  hosts: node
  gather_facts: no
  tasks:
    - name: process kill list
      shell: "ps -fu nobody |grep -w {{ network_name }} |awk '{print $2}'"
      #shell: "ps -ef | grep -v grep | grep -w {{ network_name }} | awk '{print $2}'"
      register: output1

    - name: debug 
      debug:
        msg: "{{ output1 }}"
        
    - name: kill!!
      shell: "kill -1 {{ output1.stdout }}" 
     
    #  #command: "ps aux |grep -i dnsmasq|grep -i {{ network_name }} |grep -i nobody  |awk '{print $2}' | xargs kill -1"
    #  shell: 'ps aux |grep -i dnsmasq|grep -i {{ network_name }} |grep -i nobody  |awk "{print $2}"'
    #  #shell: 'ps aux |grep -i dnsmasq|grep -i {{ network_name }} |grep -i nobody  |awk "{print $2}" | xargs kill -1'
    #  register: output1
    #- name: debug 
    #  debug:
    #    msg: "{{ output1 }}"
