---
- name: network bridge create 
  user: root
  hosts: node
  gather_facts: no
  vars:
      - uuid1: "{{ 9999999999999999999999 | random | to_uuid  }}" 
  vars_files:
      - vars/default.yml
  tasks:
      - name: directory create
        file: 
          path: "{{ PWD }}/cloud-init/"
          state: directory

      - name: bridge exist check 
        shell: "virsh net-list |grep -w {{ network_name }} "
        register: bridge_exist_check
        ignore_errors: yes

      - name: bridge name define 
        shell: "N=`ip link  |awk -F: '{print $2}' |grep -iv 'nic'|grep -i virbr | sort -V |tail -n1 |cut -c 7-` ; ((N++)) ; echo $N"
        register: bridge_number
        when: bridge_exist_check.failed 

      - name: create mac address 
        shell: " printf '52:54:%02x:%02x:%02x:%02x\n' $[RANDOM%256]  $[RANDOM%256]  $[RANDOM%256] $[RANDOM%256]"
        register: mac_address1
        when: bridge_exist_check.failed

      - name: virsh net create 
        template:
          src: templates/network.j2
          dest: /youngju1/cloud-init/createGuestVM/bridge.xml
        when: bridge_exist_check.failed 
          
      - name: network create 
        shell: virsh net-define /youngju1/cloud-init/createGuestVM/bridge.xml
        when: bridge_exist_check.failed

      - name: network auto start
        shell: "virsh net-autostart {{ network_name }}"
        when: bridge_exist_check.failed 

      - name: network start 
        shell: "virsh net-start {{ network_name }}"
        when: bridge_exist_check.failed 

- name: manage libvirt guests
  user: root
  hosts: vms
  gather_facts: no
  vars_files:
      - vars/default.yml
      - vars/guest.yml
  tasks:
      - name: start libvirtd
        service: name=libvirtd state=started enabled=yes
        register: libvirtd

      - name: create directory
        file: path={{ image_file_path }} state=directory mode=0755

      - name: wait for libvirtd to get up
        pause: seconds=30
        when: libvirtd.changed

      - name: get list of vms
        virt: command=list_vms
        register: virt_vms

      - name: create user-date directory 
        file: 
          path: "{{ PWD }}/cloud-init/{{ inventory_hostname }}"
          state: directory 

      - name: create user-data
        template: src=templates/user-data.j2 dest={{ PWD }}/cloud-init/{{ inventory_hostname }}/user-data

      - name: create meta-data
        template: src=templates/meta-data.j2 dest={{ PWD }}/cloud-init/{{ inventory_hostname }}/meta-data

      - name : create cloud-init iso
        shell: /bin/bash -c 'genisoimage -output {{ image_file_path }}/{{ inventory_hostname }}-{{ disk.cloud_init }} -volid cidata -joliet -r {{ PWD }}/cloud-init/{{ inventory_hostname }}/user-data  {{ PWD }}/cloud-init/{{ inventory_hostname }}/meta-data'

      - name: Check image  exists
        stat:
          path: "{{ image_file_path }}/{{ inventory_hostname }}.qcow2"
        register: image_exist

      - name: backing image create 
        shell: qemu-img create -b {{ image_file_path }}/{{ cloud_image }} {{ image_file_path }}/{{ inventory_hostname }}.qcow2 -f qcow2 {{ disk_size }}G
        when:
          - disk_size 
          - not image_exist.stat.exists

      - name: change permission 
        file: 
          path: "{{ image_file_path }}/{{ inventory_hostname }}.qcow2"
          owner: qemu
          group: qemu 

     # - name: resize image
     #   shell: qemu-img resize {{ image_file_path }}/{{ inventory_hostname }}.qcow2 +{{ disk_size }}G
     #   when: disk_size

      - name: create vm
        command: virt-install --import 
                 --name {{ inventory_hostname }}
                 --ram  {{ mem }}
                 --vcpus {{ cpu }}
                 --os-type {{ os.type }}
                 --os-variant {{ os.variant }}
                 --cpu host-passthrough
                 --disk {{ image_file_path }}/{{ inventory_hostname }}.qcow2,format=qcow2,bus=virtio
                 --disk {{ image_file_path }}/{{ inventory_hostname }}-{{ disk.cloud_init }},device=cdrom
                 --network network={{ network_name }},model=virtio
                 --network network={{ network_name }},model=virtio
                 --network network={{ network_name }},model=virtio
                 --network network={{ network_name }},model=virtio
                 --network network={{ network_name }},model=virtio
                 --network bridge=br0,model=virtio
                 --graphics vnc
                 --{{virt_hypervisor}}
                 --virt-type {{ virt_type }}
                 --noautoconsole
        when: inventory_hostname not in virt_vms.list_vms
        with_items: guests

      - name: get guest info
        virt: command=info
        register: virt_info

      - name: make sure all vms are running
        virt: name={{ inventory_hostname }} command=start
        when: virt_info[inventory_hostname]['state'] != 'running'
        with_items: guests

- name: add hosts playbook 
  user: root
  hosts: vms
  gather_facts: no
  vars_files:
      - vars/default.yml
      - vars/guest.yml
  serial: 1
  tasks:
      - name: add hosts 
        lineinfile: 
          path: /etc/hosts
          line: "{{ network_ipaddr }}     {{ inventory_hostname }}"
          state: present 

- name: ceph add storage device 
  hosts: ceph
  gather_facts: no
  vars:
      - disk_size2: 10
  vars_files:
      - vars/default.yml
      - vars/guest.yml
  tasks:
      - name: Check image  exists
        stat:
          path: "{{ image_file_path }}/{{ inventory_hostname }}_1.qcow2"
        register: image_exist1

      - stat:
          path: "{{ image_file_path }}/{{ inventory_hostname }}_2.qcow2"
        register: image_exist2

      - stat:
          path: "{{ image_file_path }}/{{ inventory_hostname }}_3.qcow2"
        register: image_exist3

      - name: storage disk image create 
        shell: "qemu-img create {{ image_file_path }}/{{ inventory_hostname }}_{{ item.num }}.qcow2 -f qcow2 {{ disk_size2 }}G"
        when:
          - disk_size2 
          - not image_exist1.stat.exists
          - not image_exist2.stat.exists
          - not image_exist3.stat.exists
        args:
          executable: /bin/bash 
        with_items:
          - { num: 1, device: vdb } 
          - { num: 2, device: vdc }
          - { num: 3, device: vdd }

      #- name: ceph storage detach 
      #  shell: "virsh detach-disk {{ inventory_hostname }} {{ item.device }} --live"
      #  args:
      #    executable: /bin/bash 
      #  with_items:
      #    - { num: 1, device: vdb }
      #    - { num: 2, device: vdc }
      #    - { num: 3, device: vdd }
      #  ignore_errors: true

      #- name: storage disk image remove
      #  file: 
      #    state: absent
      #    path: "{{ image_file_path }}/{{ inventory_hostname }}_{{ item.num }}.qcow2"
      #  with_items:
      #    #- "1" 
      #    #- "2"
      #    #- "3"
      #    - { num: 1, device: vdb } 
      #    - { num: 2, device: vdc }
      #    - { num: 3, device: vdd }

      - name: ceph storage attach 
        shell: "virsh attach-disk {{ inventory_hostname }} {{ image_file_path }}/{{ inventory_hostname }}_{{ item.num }}.qcow2 {{ item.device }} --live  --driver qemu --subdriver qcow2 --targetbus virtio"
        args:
          executable: /bin/bash 
        with_items:
          - { num: 1, device: vdb }
          - { num: 2, device: vdc }
          - { num: 3, device: vdd }
        ignore_errors: yes

- name: post tasks
  hosts: node
  gather_facts: no
  tasks: 
    - name: network restart prepair
      shell: "ps -fu nobody |grep -w {{ network_name }} |awk '{print $2}'"
      register: output1
        
    - name: network restart 
      shell: "pkill -1 dnsmasq"
      args:
        executable: /bin/bash 

